services:
  postgresdb:
    image: postgres
    container_name: pgdb
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: tesca
      POSTGRES_PASSWORD: tesca
      POSTGRES_DB: tesca
